### ISSUE TITLE
Help for translation

### ISSUE THREAD

**Issue by Galixte** [tas2580/phpBB-3.1-Content-Security-Policy#1]
Hi,

i want to translate this extension but the languages files DE and EN have not the good text. Could you verify your files. 

Best regards.

**Comment by Galixte** [comment]
Have you read this ?

**Comment by tas2580** [comment]
Oh sory I havn't seen this. I will check it in the next days.

**Comment by Galixte** [comment]
Hi @tas2580,

could you take a look ?

**Comment by Galixte** [comment]
Hi @tas2580,

please, could you fix this issue ?

**Comment by Galixte** [comment]
Hi @tas2580,

please, could you fix this issue ?

**Comment by tas2580** [comment]
I made an English translation, I hope you can work with this.

**Comment by Galixte** [comment]
Thanks i will. ;)
